apiVersion: apps/v1
kind: Deployment
metadata:
  name: mrdevopsapp
  labels:
    app: mrdevopsapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mrdevopsapp
  template:
    metadata:
      labels:
        app: mrdevopsapp
    spec:
      containers:
      - name: mrdevopsapp
        image: wfgamal/mrdevopsapp
        ports:
        - containerPort: 8080